package main

import (
	"net/http"
	"os"

	_ "hello/docs" // docs is generated by Swag CLI, you have to import it.

	"github.com/labstack/echo/v4"
	echoSwagger "github.com/swaggo/echo-swagger"
)

// @title Hello API
// @version 1.0
// @description This is a sample server Hello server.
// @host localhost:8080
// @BasePath /
func main() {
	e := echo.New()

	e.GET("/hello", helloHandler)
	e.GET("/swagger/*", echoSwagger.WrapHandler)

	port := os.Getenv("PORT")
	if port == "" {
		port = "8080"
	}

	e.Logger.Fatal(e.Start(":" + port))
}

// @Summary Show hello message
// @Description get hello world message
// @Tags hello
// @Accept  json
// @Produce  json
// @Success 200 {object} map[string]string
// @Router /hello [get]
func helloHandler(c echo.Context) error {
	return c.JSON(http.StatusOK, map[string]string{
		"message": "hello world",
	})
}
